apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-ebs
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0c4076112c19e7996
---
# PersistentVolumeClaim is requested to  PersistentVolume ,to storage the requst from pod coming data.
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-ebs
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: static-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: static-ebs
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts: #docker run -v hostport:container port
        - name: static-ebs
          mountPath: /usr/share/nginx/html
  volumes:
    - name: static-ebs
      persistentVolumeClaim:
        claimName: static-ebs