apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-ebs
spec:
  storageClassName: "expense-ebs" 
  volumeName: dynamic-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: dynamic-ebs
  labels:
    purpose: dynamic-ebs
spec:
  # nodeSelector:
  #     topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
      volumeMounts: #docker run -v hostport:container port
        - name: dynamic-ebs
          mountPath: /usr/share/nginx/html
  volumes:
    - name: dynamic-ebs
      persistentVolumeClaim:
        claimName: dynamic-ebs
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: dynamic-ebs
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #service port 
    targetPort: 80 # container port
    nodePort: 30007