apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-expense
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-06e9baabbb6670bb6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-expense
spec:
  volumeName: efs-expense
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static
  labels:
    purpose: efs-static
spec:
  # nodeSelector:
  #     topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
      volumeMounts: #docker run -v hostport:container port
        - name: efs-expense
          mountPath: /usr/share/nginx/html
  volumes:
    - name: efs-expense
      persistentVolumeClaim:
        claimName: efs-expense
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: static-efs
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #service port 
    targetPort: 80 # container port
    nodePort: 30007