kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: expense-efs-045
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSyste directoryPerms: "700" # mount points creation purpose we have to use 700
  mId: fs-01c3bf715b12a40e3
  basePath: "/expense" # optional
  