kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: expense-efs-045
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-01c3bf715b12a40e3
  basePath: "/expense" # optional
  