apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dynamic-efs
spec:
  storageClassName: "expense-efs-045" 
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: efs-dynamic
  labels:
    purpose: efs-dynamic
spec:
  # nodeSelector:
  #     topology.kubernetes.io/zone: us-east-1f
  containers:
    - name: nginx
      image: nginx
      volumeMounts: #docker run -v hostport:container port
        - name: dynamic-efs
          mountPath: /usr/share/nginx/html
  volumes:
    - name: dynamic-efs
      persistentVolumeClaim:
        claimName: dynamic-efs
---
apiVersion: v1
kind: Service 
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
    purpose: efs-dynamic
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80 #service port 
    targetPort: 80 # container port
    nodePort: 30007